pipeline {
    agent any

    environment {
        IMAGE_NAME = "your-dockerhub-username/flask-cicd-pipeline"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/your-username/flask-cicd-devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    script {
                        sh 'docker build -t $IMAGE_NAME .'
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        sh 'docker push $IMAGE_NAME'
                    }
                }
            }
        }
    }
}
